Вещицький, Городній, Міюц, ТО-81, Mongo
DGrudzynskyi/TicketsDemo pull request #24
Opened 2020-11-01 17:42 UTC by anasteyshaq

Вроде всё сделали, но выдаёт ошибку. Попытки пофиксить завершились провалом.
![image](https://user-images.githubusercontent.com/69891917/97810017-89981c80-1c79-11eb-89bf-cfa02e3dd5ab.png)
![image](https://user-images.githubusercontent.com/69891917/97810047-bcdaab80-1c79-11eb-9c94-68e99a0a6ddd.png)

2020-11-03 21:24 UTC, anasteyshaq commented
Перезалили документы в базу Монго. Ошибки больше нет.

2020-11-04 10:38 UTC, DGrudzynskyi requested changes

2020-11-04 10:38 UTC, DGrudzynskyi commented on TicketsDemo.Mongo/Repositories/MongoTrainRepository.cs
> +            var train = ctx.Trains.Find(new BsonDocument()).ToList();
here Carriage is not identified for place objects and
and Train is not identified for Cariage objects, so do this the same inverse assotiations assignments done in GetTrainDetails

2020-11-04 10:38 UTC, DGrudzynskyi commented on TicketsDemo/App_Start/NinjectWebCommon.cs
>              kernel.Bind<IPriceCalculationStrategy>().To<DefaultPriceCalculationStrategy>();
still using DefaultPriceCalculationStrategy, newly created ones are not registered and subsequently are not used

2020-11-04 11:16 UTC, DGrudzynskyi commented on TicketsDemo.Mongo/Repositories/MongoTrainRepository.cs
> +        private Train TrainInitialization(Train train)
private functions to be defined 'below' public ones in order to make class interface easily easier to track.

2020-11-11 11:11 UTC, closed without merging