Вещицький, Городній, Міюц ТО-81
DGrudzynskyi/TicketsDemo pull request #3
Opened 2020-10-06 08:25 UTC by anasteyshaq

2020-10-07 08:10 UTC, DGrudzynskyi requested changes

2020-10-07 08:10 UTC, DGrudzynskyi commented on TicketsDemo/App_Start/TicketServiceLoggingDecorator.cs
> +                sw.WriteLine("Successfully bought a ticket for reservationId {0}, firstName {1}, lastName {2}", reservationId, firstName, lastName);
в єтот момент времени, на самом деле, билет ещё не куплен.

Он будет куплен только тогда, когда выполнится код в строке 26.
Соответственно, в поточной строке вы должны логировать строку "An attempt to buy ticket .... параметры ..."

В случае успешной попытки -  "Succesfully bought ticket .... параметры ..."

В случае неудачной попытки (исключение выброшено при выполнении строки 26) -  "Error while creating ticket 
 .... параметры ... ... текст ошибки ..."

2020-10-07 08:10 UTC, DGrudzynskyi commented on TicketsDemo/Log_Debug.txt
> +Successfully bought a ticket for reservationId 9, firstName Larisa, lastName Denisivna
добавьте файл Log_Debug.txt в .gitignore что-бы избежать его добавления в систему контроля версий. Лог работы программы это не часть кода програмы и соответсвенно он не должен быть версирован.

2020-10-07 08:10 UTC, DGrudzynskyi commented on TicketsDemo/TicketsDemo.csproj
> +    <Reference Include="DnsClient, Version=1.0.7.0, Culture=neutral, PublicKeyToken=4574bb5573c51424, processorArchitecture=MSIL">
зачем вам DnsClient?

2020-10-07 08:10 UTC, DGrudzynskyi commented on TicketsDemo/App_Start/TicketServiceLoggingDecorator.cs
> +            string fullPath = HttpContext.Current.Server.MapPath("~/") + fileName;
В текущей реализации TicketServiceLoggingDecorator отвечает и за то, "что" мы логгируем. И за то "как" мы логгируем.

Вынесите вашу реализацию логгирования в реализацию интерфейса ILogger (обзовите её например просто Logger) и используйте этот сервис внутри декоратора.

2020-10-07 08:30 UTC, anasteyshaq commented on TicketsDemo/TicketsDemo.csproj
> +    <Reference Include="DnsClient, Version=1.0.7.0, Culture=neutral, PublicKeyToken=4574bb5573c51424, processorArchitecture=MSIL">
Есть подозрение что он подкачался вместе с драйверами для MongoDB

2020-10-07 09:25 UTC, DGrudzynskyi commented on TicketsDemo/TicketsDemo.csproj
> +    <Reference Include="DnsClient, Version=1.0.7.0, Culture=neutral, PublicKeyToken=4574bb5573c51424, processorArchitecture=MSIL">
надо проверить - удалите его и проверьте что монго работает. Если без него не работает то пусть так и будет.

2020-10-12 15:33 UTC, anasteyshaq commented on TicketsDemo/App_Start/TicketServiceLoggingDecorator.cs
> +            string fullPath = HttpContext.Current.Server.MapPath("~/") + fileName;
Создали класс Logger (скриншот 2), в котором реализован метод Log. Не совсем понятно теперь где именно его нужно вызывать в декораторе (скриншот 1) и каким образом.
![1](https://user-images.githubusercontent.com/69891917/95764372-0fe3c300-0cb9-11eb-8e36-5232a915486c.png)
![2](https://user-images.githubusercontent.com/69891917/95764374-107c5980-0cb9-11eb-8c77-0953fef5cb85.png)

2020-10-18 10:12 UTC, closed without merging