ReservationServiceLoggingDecorator
DGrudzynskyi/TicketsDemo pull request #4
Opened 2020-10-06 15:21 UTC by Kychinska

Добрий вечір! Перевірте, будь ласка, декоратор для резервації місця.
Бригада 4, Кучинська К.А., ТО-81

2020-10-07 08:14 UTC, DGrudzynskyi requested changes

2020-10-07 08:14 UTC, DGrudzynskyi commented on TicketsDemo/log.txt
> +Action time 05.10.2020 13:01:37: Successful place reservation: runDate:18.10.2020 18:18:42, place:49, carriage:1, runId:2, reservationDate:05.10.2020 13:01:37
добавьте файл log.txt в .gitignore что-бы избежать его добавления в систему контроля версий. Лог работы программы это не часть кода програмы и соответсвенно он не должен быть версирован.

2020-10-07 08:14 UTC, DGrudzynskyi commented on TicketsDemo.Domain/DefaultImplementations/ReservationServiceLoggingDecorator.cs
> +        { using (StreamWriter streamWriter = File.AppendText(_logLocation))
В текущей реализации ReservationServiceLoggingDecorator отвечает и за то, "что" мы логгируем. И за то "как" мы логгируем.

Представим что логгировать нужно не-только-резервации, при текущем подходе єто значит что для каждого другого места которое мы будем логгировать потребуется указывать место "куда" логгировать. Т.е. информация будет дублироватся в разных местах, что невозможно поддерживать. А теперь представьте что в один прекрасный момент логгировать нужно не в файл а c помощью http вызова. Опять же - придётся перелопачивать "все" места где происходит логгирование.

Вынесите вашу реализацию логгирования в реализацию интерфейса ILogger (обзовите её например просто Logger) и используйте этот сервис внутри декоратора.

2020-10-13 13:38 UTC, Kychinska commented
Я все виправила, перевірьте, будь ласка.

2020-10-20 10:41 UTC, closed without merging