Squad #2 - Booking service feature
DGrudzynskyi/TicketsDemo pull request #6
Opened 2020-10-19 20:17 UTC by DZinchenko

Понятия не имею,по какой причине при доставании из базы BookingService-ов не подтягиваются HostAgency. Пришлось вставлять их вручную. А так, все работает.

2020-10-20 18:10 UTC, DZinchenko commented
Таки понял почему. Если бы HostAgency сами подтягивались, то все это дело уходило бы в бесконечный цикл. Так или иначе, считаю что подставлять их при вызове в репозитори имееет некий смысл.

2020-10-21 09:45 UTC, DGrudzynskyi commented on TicketsDemo.Data/Entities/BookingServiceAggregate/BookingService.cs
> +        public BookingAgency HostAgency { get; set; }
Either match the names HostAgency and  BookingAgencyId in order to map association to it's key
OR
use fluent api to do the matching (something like 

            modelBuilder.Entity<BookingService>().HasRequired(x => x.HostAgency).WithMany(x => x.BookingServices).HasForeignKey(x => x.BookingAgencyId)WillCascadeOnDelete(false);

2020-10-21 20:08 UTC, DZinchenko commented
About the BookingService.HostAgency not being pulled from the DB and assigned to the object 
I've tried matching the names(both ways), I've tried resolving this problem through Fluent API, I've tried to rollback the DB to the point, where BookingService and BookingAgency didn't even exist and matched the names/ used Fluent API. None of that did work.
Still pulling HostAgencies and assigning them to the object manually in the BookingServiceRepository.

2020-10-26 21:00 UTC, DGrudzynskyi commented
> About the BookingService.HostAgency not being pulled from the DB and assigned to the object
> I've tried matching the names(both ways), I've tried resolving this problem through Fluent API, I've tried to rollback the DB to the point, where BookingService and BookingAgency didn't even exist and matched the names/ used Fluent API. None of that did work. I don't know how to fix this.
> Still pulling HostAgencies and assigning them to the object manually in the BookingServiceRepository.

well, something went wrong... let's fix it on wednesday

2020-10-26 21:04 UTC, DGrudzynskyi requested changes

2020-10-26 21:04 UTC, DGrudzynskyi commented on TicketsDemo.Data/Repositories/IBookingServiceRepository.cs
> +    public interface IBookingServiceRepository
Увас два репозитория для одного аггрегата. Я не оставлял єтот коммент ранее т.к. мы только сегодня нормально прошлись по понятию агрегата и следующем из этого понятия структурировании кода.

2020-10-26 21:04 UTC, DGrudzynskyi commented on TicketsDemo.Domain/DefaultImplementations/PriceCalculation/BookingServicePriceCalculationStrategy.cs
> +    public class BookingServicePriceCalculationStrategy : IPriceCalculationStrategy
тут все ровно аккуратно

2020-10-26 21:04 UTC, DGrudzynskyi commented on TicketsDemo.Domain/DefaultImplementations/PriceCalculation/FinalPriceCalculationStrategy.cs
> +    public class FinalPriceCalculationStrategy : IPriceCalculationStrategy
Текс, а зачем вам это? Подумайте ещё раз нужна ли вам эта пакость просто проговорив словами что делает каждая из ваших стратегий.

2020-10-26 21:10 UTC, DGrudzynskyi commented on TicketsDemo.Domain/DefaultImplementations/PriceCalculation/FinalPriceCalculationStrategy.cs
> +    public class FinalPriceCalculationStrategy : IPriceCalculationStrategy
Ха, вижу что у вас стратегия рассчёта цены "для агенства" только "добавляет" свой компонент. В этом случае все хорошо и данный класс нужен и полезен. My bad.

2020-10-26 21:11 UTC, DGrudzynskyi commented on TicketsDemo.Domain/DefaultImplementations/PriceCalculation/FinalPriceCalculationStrategy.cs
> +    public class FinalPriceCalculationStrategy : IPriceCalculationStrategy
Upd. my bad все на своём месте, я сначала подумал что стратегия которая декорирует базовую ее компонент "тоже" возвращает, а она его только "использует"

2020-10-28 10:15 UTC, DGrudzynskyi commented on TicketsDemo/Controllers/ScheduleController.cs
> +            _bookingServiceRepo.Get(1);
WAT is this?

2020-11-04 10:44 UTC, DGrudzynskyi requested changes

2020-11-04 10:44 UTC, DGrudzynskyi commented on TicketsDemo.Data/Entities/TicketAggregate/PriceComponentDO.cs
> +    public class PriceComponentDO
please cleanup unused code

2020-11-04 10:44 UTC, DGrudzynskyi commented on TicketsDemo/Controllers/RunController.cs
> +            var tick = _tickServ.CreateTicket(model.ReservationId,model.FirstName,model.LastName, parameters);
Functions shall never expect half-way-initialized DTO objects.

If some fields of DTO are not needed - create another DTO without these fields (in your case - just add BookingServiceId as int argument to function)

ALternatively, fill 'all' the properties of PriceCalculationParameters 'before' calling CreateTicket

2020-11-04 11:14 UTC, closed without merging